services:
    jgp_ajax_modals.ajax_views.factory:
        class: Jagilpe\AjaxModalsBundle\View\AjaxViewFactory

    # Twig extension
    jgp_ajax_modals.twig_extension:
        class: Jagilpe\AjaxModalsBundle\Twig\JagilpeAjaxModalsExtension
        public: false
        tags:
            - { name: twig.extension }

    jgp_ajax_modals.ajax_view_button:
        class: Jagilpe\AjaxModalsBundle\View\AjaxViewButton
        public: true
        arguments:
            - '@translator'

    # Event listeners
    jgp_ajax_modals.ajax_view_controller_listener:
        class: Jagilpe\AjaxModalsBundle\EventListener\AjaxViewControllerEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.view }
            
    Jagilpe\AjaxModalsBundle\View\AjaxViewFactory:
        alias: jgp_ajax_modals.ajax_views.factory
        public: false

    Jagilpe\AjaxModalsBundle\EventListener\AjaxViewControllerEventListener:
        alias: jgp_ajax_modals.ajax_view_controller_listener
        public: false
